# Generated by Django 4.2.4 on 2023-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LongToShort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField(max_length=500)),
                ("short_url", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("clicks", models.IntegerField(default=True)),
                ("time", models.TimeField(auto_now_add=True))
            ],
        ),
    ]
